[35기 박서윤] 프로젝트 모델링
wecode-bootcamp-korea/35-1st-Dev-Island-backend pull request #6
Opened 2022-07-19 09:21 UTC by happy-tiger212

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 프로젝트 모델링
<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
- carts modeling (makemigrations & migrate)
- products modeling (makemigrations & migrate)
- orders modeling (makemigrations & migrate)

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
없음

<br />

## :: 기타 질문 및 특이 사항
없음

2022-07-19 09:28 UTC, bigfanoftim requested changes

2022-07-19 09:28 UTC, bigfanoftim commented on orders/models.py
> +from tkinter import CASCADE
```suggestion
```
사용하지 않는 import는 지워주세요.

2022-07-19 09:28 UTC, bigfanoftim commented on orders/models.py
> +class Order_Product(models.Model):
```suggestion
class OrderProduct(models.Model):
```
Class 이름에는 언더바(_)를 사용하지 않습니다!

2022-07-19 09:28 UTC, bigfanoftim commented on orders/models.py
> +    order_status = models.CharField(max_length=100)
```suggestion
    order_status = models.ForeignKey(max_length=100)
```
status도 테이블로 만들어서 데이터 관리해주세요.

2022-07-19 09:28 UTC, bigfanoftim commented on products/models.py
> +    price        = models.IntegerField()
```suggestion
    price        = models.DecimalField(...)
```
price는 DecimalField로 사용해주세요.

2022-07-20 01:48 UTC, bigfanoftim requested changes

2022-07-20 01:48 UTC, bigfanoftim commented on orders/models.py
> +class Delivery(models.Model):
```suggestion
class OrderStatus(models.Model):
```
모델 클래스명이 좀더 명확해야할 것 같습니다.

2022-07-20 01:48 UTC, bigfanoftim commented on orders/models.py
> +    order_product_status = models.ForeignKey('Delivery', on_delete=models.CASCADE)
order와 product의 상태값은 아마 전혀 다른 상태값을 가질텐데 하나의 테이블을 참조하는 의미가 있을까요?

2022-07-20 02:06 UTC, happy-tiger212 commented on orders/models.py
> +    order_product_status = models.ForeignKey('Delivery', on_delete=models.CASCADE)
product와 같이, order class의 status도 Delivery(배송전, 중 , 완료) 중 하나여야 한다고 생각하여, order와 product가 하나의 테이블을 참조하도록 하였습니다.
order가 다른 상태값을 가진다면 어떤 상태값을 말씀하시는건지 알려주실 수 있나요?

2022-07-20 06:26 UTC, bigfanoftim commented on orders/models.py
> +    order_product_status = models.ForeignKey('Delivery', on_delete=models.CASCADE)
주문에는 주문완료 주문취소 등 다른 상태가 있을거고 배송이랑은 관계가 없을 것 같아요!

2022-07-20 10:17 UTC, bigfanoftim approved these changes
LGTM 👍

2022-07-20 10:17 UTC, merged